# Generated by Django 4.1 on 2022-09-10 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myblog',
            name='images',
        ),
    ]
