# Generated by Django 4.1 on 2022-09-10 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0002_remove_myblog_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='myblog',
            name='images',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m'),
        ),
    ]
