# Generated by Django 4.1 on 2022-09-12 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MyBlog", "0003_myblog_images"),
    ]

    operations = [
        migrations.RemoveField(model_name="myblog", name="subject",),
    ]
