# Generated by Django 4.1 on 2022-09-12 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MyBlog", "0004_remove_myblog_subject"),
    ]

    operations = [
        migrations.RenameModel(old_name="Myblog", new_name="Post",),
    ]
