# Generated by Django 4.1 on 2022-09-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MyBlog", "0005_rename_myblog_post"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post", old_name="images", new_name="post_image",
        ),
        migrations.AlterField(
            model_name="post",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
