# Generated by Django 4.1 on 2022-09-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MyBlog", "0006_rename_images_post_post_image_alter_post_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="home_images",
            field=models.ImageField(blank=True, upload_to="home_photos/%Y/%m"),
        ),
    ]
