# Generated by Django 4.1 on 2022-09-12 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MyBlog", "0007_post_home_images"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="home_images",),
    ]
